### PR TITLE
candy cane swapped for non-repeating vertical bands

### PR DESCRIPTION
**Pull request by HCAWN**
I love being able to read the titles of events in my calendar now but the striped angled background can be a bit distracting. I've changed the background styling to look more like an unmodified calendar:

From
image
To
image

### CODE REVIEW

**Comment by HCAWN** [comment]
image
Events not responded to or declined now appear striped, allowing even title to be read (rather than white background with border)

Also added Manifest V3 support

**Comment by HCAWN** [comment]
Some ui fixes (white text not coloured)
I've made the original events `opacity:0` now instead of `visibility: hidden` and repositioned them to align with the evenly distributed gradient so users can click on the original calendar events. This fixes issue [86](https://github.com/imightbeamy/gcal-multical-event-merge/issues/86)
also issue  [78](https://github.com/imightbeamy/gcal-multical-event-merge/issues/78) styling fixed with previous commit
@zlanich @danyal

**Comment by eoinbutler** [comment]
I really like the striped candy-cane over the striped vertical style. I would suggest making this an option so as to maintain reverse compatibility.

**Comment by HCAWN** [comment]
@eoinbutler 
Good idea, choice is always better, I've made a popup with that toggle and also set the stage for more options to be put into the popup:

https://github.com/HCAWN/gcal-multical-event-merge/pull/4

**Comment by michaelblyons** [comment]
Do you want issue reports? GitHub disables the issue tracker on forks by default, but you can turn it back on.

**Comment by HCAWN** [comment]
@michaelblyons I've just enabled, please fire away!
With no word from Amy, I'm going to stop pushing to this PR and keep further updates on my fork (and my chrome extension link)

**Pull request closed without merging**
